package com.android.approjects.grafika;

import android.app.ListActivity;
import android.os.Bundle;

import com.android.approjects.R;

import androidx.annotation.Nullable;

/**
 * Manages content generated by the app.
 *
 * <p>
 *     Originally this was going to prepare stuff on demand, but it's easier to just
 *     create it all up front on first launch.
 * </p>
 *
 * Class is thread-safe.
 */

public class GrafikaActivity extends ListActivity {
    public static final String TAG = "Grafika";

    // map keys
    private static final String TITLE = "title";
    private static final String DESCRIPTION = "description";
    private static final String CLASS_NAME = "class_name";

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // setContentView(R.layout.activity_grafika);

        // One-time singleton initialization; requires activity context to get file location.
        ContentManager.initialize(this);


    }
}
